added miseq edit for deepvariant nextflow pipeline
AWGL/IlluminaQC-WREN pull request #11
Opened 2023-11-24 12:01 UTC by Istaisa

Added line to MiSeq edit to count for new FH deepvariant_nextflow pipeline being run on the MiSeq.

Doesn't need merging until pipeline goes live.

2023-12-01 10:34 UTC, SophieS9 requested changes
Happy with the changes as long as the sample sheet generator has been set up to encode as dn. 

Can we merge to development instead of straight to master though?

2023-12-01 11:06 UTC, Istaisa commented
updated branch.
autoqc changes in https://github.com/AWGL/auto_qc/pull/164 approved but won't be deployed until go live

2023-12-01 11:11 UTC, SophieS9 approved these changes

2025-01-24 09:25 UTC, SophieS9 commented
No longer relevant as MiSeq not in use

2025-01-24 09:25 UTC, closed without merging